# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.runs/synth_1/chip_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.cache/wt [current_project]
set_property parent.project_path /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog /mnt/d/fpga-rocket-chip/verilog/utils/nasti_lite_bridge/nasti_request.vh
read_mem /mnt/d/fpga-rocket-chip/firmware/firmware.hex
read_verilog -library xil_defaultlib -sv {
  /mnt/d/fpga-rocket-chip/verilog/utils/nasti_lite_bridge/nasti_lite_bridge.sv
  /mnt/d/fpga-rocket-chip/verilog/utils/nasti_lite_bridge/nasti_lite_reader.sv
  /mnt/d/fpga-rocket-chip/verilog/utils/nasti_lite_bridge/nasti_lite_writer.sv
}
read_verilog -library xil_defaultlib {
  /mnt/d/fpga-rocket-chip/verilog/AXIMem.v
  /mnt/d/fpga-rocket-chip/verilog/AXIMmio.v
  /mnt/d/fpga-rocket-chip/verilog/utils/AsyncResetReg.v
  /mnt/d/fpga-rocket-chip/verilog/utils/EICG_wrapper.v
  /mnt/d/fpga-rocket-chip/verilog/peri/JtagTunnel.v
  /mnt/d/fpga-rocket-chip/verilog/peri/bram.v
  /mnt/d/fpga-rocket-chip/verilog/peri/bram_storage.v
  /mnt/d/fpga-rocket-chip/rocket-chip/vsim/generated-src/freechips.rocketchip.system.DefaultNexys4DDRConfig.v
  /mnt/d/fpga-rocket-chip/verilog/utils/narrower.v
  /mnt/d/fpga-rocket-chip/verilog/utils/plusarg_reader.v
  /mnt/d/fpga-rocket-chip/verilog/peri/spi.v
  /mnt/d/fpga-rocket-chip/verilog/utils/sram_modified.v
  /mnt/d/fpga-rocket-chip/verilog/peri/uart.v
  /mnt/d/fpga-rocket-chip/verilog/chip_top.v
}
read_ip -quiet /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.srcs/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0.xci
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/axi_quad_spi_0/axi_quad_spi_0_clocks.xdc]

read_ip -quiet /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.srcs/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0.xci
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/axi_bram_ctrl_0/axi_bram_ctrl_0_ooc.xdc]

read_ip -quiet /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.srcs/sources_1/ip/axi_uart16550_0/axi_uart16550_0.xci
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/axi_uart16550_0/axi_uart16550_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/axi_uart16550_0/axi_uart16550_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/axi_uart16550_0/axi_uart16550_0.xdc]

read_ip -quiet /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.srcs/sources_1/ip/axi_crossbar_0/axi_crossbar_0.xci
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/axi_crossbar_0/axi_crossbar_0_ooc.xdc]

read_ip -quiet /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.srcs/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0.xci
set_property used_in_synthesis false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0_ooc.xdc]

read_ip -quiet /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /mnt/d/fpga-rocket-chip/nexys4ddr/nexys4ddr.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /mnt/d/fpga-rocket-chip/constraints/nexys4ddr.xdc
set_property used_in_implementation false [get_files /mnt/d/fpga-rocket-chip/constraints/nexys4ddr.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top chip_top -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef chip_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file chip_top_utilization_synth.rpt -pb chip_top_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
